name: "\U0001f4a1 Request a New Topic"
description: "Submit a request to add a new trading topic or chapter."
title: "[New Topic]: "
labels: ["enhancement", "new-topic"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Trading Wala Guru! Please make sure the topic doesn't already exist.
  - type: input
    id: topic_name
    attributes:
      label: Which Topic / Chapter do you want to learn?
      description: e.g. "Advanced Iron Condor Strategies"
      placeholder: Complete topic name
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Why do you want this topic?
      description: Explain what you specifically want to learn about this topic.
    validations:
      required: true
