name: "\U0001f41b Report a Typo / Spelling Mistake"
description: "Found a mistake in spelling, grammar, or formula?"
title: "[Correction]: "
labels: ["bug", "correction"]
body:
  - type: input
    id: File
    attributes:
      label: Which File / Folder has the mistake?
      description: Write the exact lesson name.
    validations:
      required: true
  - type: textarea
    id: Fix
    attributes:
      label: What needs to be fixed?
      description: Write what is written currently vs what should be written.
    validations:
      required: true
